/*
 * Lee Li Dice Game Program from 10/30/2018 
 */

/**
 *
 * @author Liqixiao
 */
public class Dicegame extends javax.swing.JFrame {

    int totalRolls = 0;
    int totalCorrect = 0;
    int totalIncorrect = 0;
    int UserGuess ;
    int diceRoll;
    double percCorrect = 0;
    
    public Dicegame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblnst1 = new javax.swing.JLabel();
        lblnst2 = new javax.swing.JLabel();
        lblUserGuess = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        btnRollDice = new javax.swing.JButton();
        lblDiceRoll = new javax.swing.JLabel();
        lblRollValue = new javax.swing.JLabel();
        lblRolls = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        lblCorrectvalue = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 51, 51));
        lblHeader.setText("Super Dice Guessing Game");

        lblnst1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        lblnst1.setForeground(new java.awt.Color(255, 0, 153));
        lblnst1.setText("Enter a number, from 1 to 6 ");

        lblnst2.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        lblnst2.setForeground(new java.awt.Color(255, 0, 153));
        lblnst2.setText("And click the roll to roll the dice");

        lblUserGuess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserGuess.setForeground(new java.awt.Color(255, 51, 51));
        lblUserGuess.setText("Your Guess");

        btnRollDice.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        btnRollDice.setForeground(new java.awt.Color(255, 51, 51));
        btnRollDice.setText("Roll Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        lblDiceRoll.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDiceRoll.setForeground(new java.awt.Color(255, 51, 51));
        lblDiceRoll.setText("Dice Roll");

        lblRollValue.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRollValue.setForeground(new java.awt.Color(51, 51, 255));

        lblRolls.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRolls.setForeground(new java.awt.Color(255, 0, 51));
        lblRolls.setText("Number of Rolls");

        lblCorrect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(255, 51, 51));
        lblCorrect.setText("Number of Correct Guesses");

        lblRollsValue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblRollsValue.setForeground(new java.awt.Color(0, 0, 255));

        lblCorrectvalue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCorrectvalue.setForeground(new java.awt.Color(0, 0, 255));

        lblIncorrect.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIncorrect.setForeground(new java.awt.Color(255, 51, 51));
        lblIncorrect.setText("Number of Incorrect Guesses");

        lblIncorrectValue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIncorrectValue.setForeground(new java.awt.Color(0, 0, 255));

        lblPercent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPercent.setForeground(new java.awt.Color(255, 51, 51));
        lblPercent.setText("Percentage of Correct Guesses");

        lblPercentValue.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPercentValue.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtUserGuess))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnRollDice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDiceRoll))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRollValue, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRolls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCorrect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addComponent(lblCorrectvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIncorrect)
                            .addComponent(lblPercent))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHeader)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblnst1)
                        .addGap(147, 147, 147))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblnst2)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHeader)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnst1)
                        .addGap(1, 1, 1)
                        .addComponent(lblnst2)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUserGuess)
                                        .addComponent(lblDiceRoll))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnRollDice)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRollValue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRolls)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCorrectvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorrect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIncorrect, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIncorrectValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(lblPercent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        
        diceRoll = (int)Math.round(Math.random()*5+1);
        lblDiceRoll.setText(String.valueOf(diceRoll));
        
        UserGuess = Integer.parseInt(txtUserGuess.getText());
        
        totalRolls = totalRolls + 1;
        
        if (diceRoll == UserGuess)
        {
            totalCorrect = totalCorrect + 1;
        }
        else
        {
            totalIncorrect = totalIncorrect + 1;
        }
        
        percCorrect = ((double)totalCorrect/(double)totalRolls)*100;
        
        percCorrect = percCorrect * 100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect/100;
        
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectvalue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText(String.valueOf(percCorrect));
        
        
    }//GEN-LAST:event_btnRollDiceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dicegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dicegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dicegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dicegame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dicegame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectvalue;
    private javax.swing.JLabel lblDiceRoll;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollValue;
    private javax.swing.JLabel lblRolls;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JLabel lblUserGuess;
    private javax.swing.JLabel lblnst1;
    private javax.swing.JLabel lblnst2;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
